добавила вёрстку первой части макета
Elena-web/New-Project pull request #2
Opened 2024-05-12 15:18 UTC by Elena-web

2024-05-13 22:52 UTC, burtovoy requested changes

2024-05-13 22:52 UTC, burtovoy commented on public/index.html
> +                    <svg class="logo" width="36" height="38" viewBox="0 0 36 38" fill="none" xmlns="http://www.w3.org/2000/svg">
давай это в файл вынесем

2024-05-14 12:52 UTC, Elena-web commented on public/index.html
> +                    <svg class="logo" width="36" height="38" viewBox="0 0 36 38" fill="none" xmlns="http://www.w3.org/2000/svg">
Саша, я не поняла, что ты имеешь в виду. Какой файл? header выносить в отдельный файл? не поняла)

2024-05-14 20:53 UTC, burtovoy requested changes

2024-05-14 20:53 UTC, burtovoy commented on public/index.html
> +                    <svg class="logo" width="36" height="38" viewBox="0 0 36 38" fill="none" xmlns="http://www.w3.org/2000/svg">
svg в файл давай сделаем, что бы код чище был )

2024-05-15 09:11 UTC, Elena-web commented on public/index.html
> +                    <svg class="logo" width="36" height="38" viewBox="0 0 36 38" fill="none" xmlns="http://www.w3.org/2000/svg">
исправила, если правильно тебя поняла)

2024-05-16 21:52 UTC, merged