Task 4
Elena-web/New-Project pull request #4
Opened 2024-05-27 07:07 UTC by Elena-web

Функция преобразующая дату и время публикации поста и текущее время в текстовый формат и тесты к ней.

2024-05-29 23:46 UTC, burtovoy commented
В pr должны быть только изменения, которые относятся к задаче

2024-05-29 23:47 UTC, burtovoy requested changes
В pr должны быть только те изменения, которые относятся к задаче

2024-05-30 18:48 UTC, Elena-web commented
> В pr должны быть только те изменения, которые относятся к задаче
 
Как мне сейчас поступить? Новую ветку создать и добавить эту функцию с тестами?

2024-05-31 00:25 UTC, burtovoy commented
Да, можно новую ветку

2024-06-09 07:30 UTC, closed without merging